
[env:heating_control]
framework = arduino
platform = espressif32
board = lolin_s3_mini ; 4 MB flash
board_build.filesystem = littlefs
; build_type = debug

build_src_filter = +<controller/*.cpp>
lib_deps =
  SimpleNode = symlink://../../../SimpleNode
extra_scripts =
  pre:../../../SimpleNode/scripts/make-build.gen.h.py

build_flags =
  -std=gnu++17
  ;-DCORE_DEBUG_LEVEL=5
build_unflags =
  -std=gnu++11

upload_speed = 921600
upload_port = /dev/ttyACM0

monitor_speed = 115200
monitor_filters =
  esp32_exception_decoder
  time


[env:heating_valves]
framework = arduino
platform = atmelavr
board = nanoatmega328new
  ; nanoatmega328 "new" because of the CH340 serial interface

build_src_filter = +<valves/*.cpp>
lib_deps = adafruit/Adafruit SleepyDog Library

monitor_speed = 115200
monitor_filters = time