; PlatformIO Project Configuration File

[env:loraRelay]
framework = arduino
platform = espressif32
board = wemos_d1_mini32 ; 4 MB flash
board_build.filesystem = littlefs
upload_speed = 921600
lib_deps =
  SimpleNode = symlink://../../../SimpleNode
build_flags =
  -std=c++17
  -std=gnu++17
build_unflags =
  -std=gnu++11
extra_scripts =
  pre:../../../SimpleNode/scripts/make-build.gen.h.py
monitor_filters = esp32_exception_decoder
